image:
  - Visual Studio 2019
  - Ubuntu2004

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019

    install:
      - set PATH=C:\Qt\Tools\mingw810_64\bin;%PATH%
      - set Boost_ROOT=C:\Libraries\boost_1_73_0

    build_script:
      - cmake -G "MinGW Makefiles" -D Qt6_DIR=C:\Qt\6.3.1\mingw_64\lib\cmake\Qt6 ..
      - cmake --build .
  
  -
    matrix:
      only:
        - image: Ubuntu2004
    
    install:
      - sudo apt update
      - sudo apt install -y mesa-common-dev libglu1-mesa-dev
      - sudo apt install -y libboost-all-dev
      - sudo apt install -y graphviz

    build_script:
      - cmake -D Qt6_DIR=$HOME/Qt/6.3.1/gcc_64/lib/cmake/Qt6 ..
      - cmake --build .

before_build:
  - mkdir build
  - cd build